### ISSUE TITLE
Feature Request: Add support for directory groups in jamfpro_account_group

### ISSUE THREAD

**Issue by ecanault** [deploymenttheory/terraform-provider-jamfpro#155]
Hi,

Is it possible to add the ability to manage LDAP or IdP groups in `jamfpro_account_group`?

This can be done with the Classic API by submitting the following datas:

```
<group>
  <name>${LDAP_GROUP}</name>
  <access_level>Full Access</access_level>
  <privilege_set>Administrator</privilege_set>
  <ldap_server>
  <id>${LDAP_ID}</id>
  </ldap_server>
</group>
```

Where:
- `LDAP_GROUP` is the name of the LDAP group
- `LDAP_ID` is the ID of the LDAP or IdP configuration in Jamf Pro (see `api/v1/cloud-idp` in Jamf Pro API for example for Entra or Google integrations)

Thanks in advance :-)
Emmanuel

**Comment by ShocOne** [comment]
Hi there, looks like an easy enough implementation, i'll take a look next week for you. Thanks

**Comment by ShocOne** [comment]
I've added support for ldap groups using a new identity_server block that can now be added to `jamfpro_account_group` . This has been added with PR #160 and is part of the v0.0.45 release. Please test and confirm. many thanks

**Comment by ecanault** [comment]
Hi @ShocOne 

Thanks a lot for this enhancement!
Just made a test : resources are correctly created, but the terraform deployment command ends up with errors:
```
╷
│ Error: Error waiting for Jamf Pro Account Group resource with ID '4' to become available after 1 retries. Last error: context deadline exceeded
│ 
│   with jamfpro_account_group.admin_group,
│   on main.tf line 38, in resource "jamfpro_account_group" "admin_group":
│   38: resource "jamfpro_account_group" "admin_group" {
│ 
╵
╷
│ Error: Error waiting for Jamf Pro Account Group resource with ID '5' to become available after 1 retries. Last error: context deadline exceeded
│ 
│   with jamfpro_account_group.auditor_group,
│   on main.tf line 47, in resource "jamfpro_account_group" "auditor_group":
│   47: resource "jamfpro_account_group" "auditor_group" {
│ 
╵
╷
│ Error: Error waiting for Jamf Pro Account Group resource with ID '6' to become available after 1 retries. Last error: context deadline exceeded
│ 
│   with jamfpro_account_group.enrollment_group,
│   on main.tf line 56, in resource "jamfpro_account_group" "enrollment_group":
│   56: resource "jamfpro_account_group" "enrollment_group" {
│ 
╵
``` 

Here are the relevant parts of my`main.tf` file:
```
terraform {
  required_providers {
    jamfpro = {
      source  = "deploymenttheory/jamfpro"
      version = "~> 0.0.45"
    }
  }
}

provider "jamfpro" {
  instance_name                = var.JAMFPRO_INSTANCE_NAME
  username                     = var.JAMFPRO_USERNAME
  password                     = var.JAMFPRO_PASSWORD
  log_level                    = "none"
  log_output_format            = "console"
  log_console_separator        = " "
  hide_sensitive_data          = true
  max_retry_attempts           = 5
  enable_dynamic_rate_limiting = false
  max_concurrent_requests      = 5
  token_refresh_buffer_period  = 10
  total_retry_duration         = 30
  custom_timeout               = 30
}

resource "jamfpro_account_group" "admin_group" {
  name          = var.SSO_ADMIN_GROUP
  access_level  = "Full Access"
  privilege_set = "Administrator"
  identity_server {
    id = 1004
  }
}

resource "jamfpro_account_group" "auditor_group" {
  name          = var.SSO_AUDIT_GROUP
  access_level  = "Full Access"
  privilege_set = "Auditor"
  identity_server {
    id = 1004
  }
}

resource "jamfpro_account_group" "enrollment_group" {
  name          = var.SSO_ENROLL_GROUP
  access_level  = "Full Access"
  privilege_set = "Enrollment Only"
  identity_server {
    id = 1004
  }
}
```

Regards,
Emmanuel

**Comment by ShocOne** [comment]
Hi Manu, I've made some changes to the provider to accommodate your ask and they will be in the next release to support iDP and LDAP. I've been focusing on the stating issues you flagged in your comments this week. Which should be resolved now.

**Comment by ecanault** [comment]
Hi @ShocOne 
Many thanks for that, I will test it ASAP.
I will have other features requests I think 🙂.

**Comment by ShocOne** [comment]
Please try the latest release v0.0.48 and let me know how you get on. My sandbox jamf environment doesn't haven't have ldap integration so im having to build off of the data model and documentation exclusively.

**Comment by ecanault** [comment]
Hi,
I have juste done a quick test : the objects create tasks take a looong time (~ 4 mn), but it works \o/
I didn't played with the new options as discussed in the Slack channel but I will do :-)
I hope to have more time next week to work on this subject.
Thanks

**Comment by ShocOne** [comment]
great. if you have any other feedback then let me know. thanks for testing

**Comment by ecanault** [comment]
[like]  Emmanuel Canault reacted to your message:
________________________________
