### ISSUE TITLE
Feature Request: Add support for restricted software records

### ISSUE THREAD

**Issue by mhrono** [deploymenttheory/terraform-provider-jamfpro#211]
Relevant jamf API docs (classic): https://developer.jamf.com/jamf-pro/reference/restrictedsoftware

Why? Because managing anything manually is frustrating! 🤣 
Joking aside, I'd like for my team or others to be able to add/change/remove restricted software records with a PR rather than having to make manual changes in jamf. This would also provide proper revision history and an audit trail.

**Comment by ShocOne** [comment]
Happy to bring this into scope for the next release / the release after. The sdk has coverage for these endpoints so it's simply a case of implementing the tf provider functionality.

**Comment by ShocOne** [comment]
this has been included in release v0.0.53 . thanks
