### ISSUE TITLE
`jamfpro_macos_configuration_profile` no longer supports `name` within `category` causing state issues

### ISSUE THREAD

**Issue by smithjw** [deploymenttheory/terraform-provider-jamfpro#226]
A recent merge breaks prior functionality without providing any migration strategy when referencing Categories.

https://github.com/deploymenttheory/terraform-provider-jamfpro/blob/b09ee722428971cdb1a2673f4bd0f73268504d4b/internal/endpoints/common/sharedschemas/category.go#L13-L17

Uncommenting these lines will allow prior configs/states to continue working until a state migration function is available for this

**Comment by ShocOne** [comment]
Category name has been restored as part of release v0.0.54. However the name field will be computed going forward as requests require ids only and we are looking to simplify/standardize upon id for referencing other resources
