### ISSUE TITLE
Configuration Profiles in state prior to 0.0.55 no longer function

### ISSUE THREAD

**Issue by smithjw** [deploymenttheory/terraform-provider-jamfpro#249]
With the new way that Configuration Profiles are functioning in `0.0.55`, profiles that were previously created throw warnings when running a new plan.

Previously the attribute `payload` was used within the `jamfpro_macos_configuration_profile` and now the attribute `payloads` is required. Can these warnings be ignored?

``` shell
│ Warning: Failed to decode resource from state
│ 
│ Error decoding "jamfpro_macos_configuration_profile.globalprotect[\"Network
│ Extension\"]" from prior state: unsupported attribute "payload"
╵
╷
│ Warning: Failed to decode resource from state
│ 
│ Error decoding "jamfpro_macos_configuration_profile.globalprotect[\"System
│ Extensions\"]" from prior state: unsupported attribute "payload"
```

**Comment by ShocOne** [comment]
We've changed the payload field name to payloads along with some other field name changes. Delete and redeploy,
