### ISSUE TITLE
Feature Request: Add support for new keys in jamfpro_account

### ISSUE THREAD

**Issue by ecanault** [deploymenttheory/terraform-provider-jamfpro#260]
Hi,

 It seems there are new keys for the `jamfpro_account` resource in the 11.5 release of Jamf Pro:

```
~ jss_actions_privileges    = [
    - "Send Device Information Command",
      # (81 unchanged elements hidden)
  ]
~ jss_settings_privileges   = [
    - "Read Login Disclaimer",
    - "Read Remote Assist",
    - "Update Login Disclaimer",
    - "Update Remote Assist",
      # (78 unchanged elements hidden)
  ]
```

Thanks!

**Comment by ShocOne** [comment]
Work has started today on updating the sdk to support 11.5. this will also include updating the provider to support relevant new permissions as per your ask. Thanks

**Comment by ShocOne** [comment]
This has been fixed in the latest release. Thanks
