### ISSUE TITLE
Feature Request: new API endpoing for packages management

### ISSUE THREAD

**Issue by ecanault** [deploymenttheory/terraform-provider-jamfpro#272]
Managing packages is working quite well as the old endpoint is still valid.

The only thing I noticed is the fact that packages are marked as `Availability Pending` for a looooong time (more than 10 or 20 minutes).

It should be a good point to implement the new Jamf Pro API endpoint in my opinion : <https://developer.jamf.com/jamf-pro/reference/get_v1-packages>

**Comment by ShocOne** [comment]
We will start looking at updates to existing endpoints to support jamf pro 11.5 onwards once we are in a steady state.  Packages will be supported in its current form until 11.6. so we have some time to update the go-api-sdk-jamfpro before starting on the provider changes

**Comment by ShocOne** [comment]
this has been added as part of release v0.1.0. thanks
