### ISSUE TITLE
Enhancement: configuration profiles

### ISSUE THREAD

**Issue by ecanault** [deploymenttheory/terraform-provider-jamfpro#274]
Well... I'm surely doing it bad, but I didn't manage to find a satisfying way to handle them.

- Why some `PayloadXxx` keys are required in `.mobileconfig` or `plist`?
 
For example `PayloadScope` must be defined AND its value must be the same than the `level` key !?

Is it possible to simplify this and for example

1. to allow the use of basic `.mobileconfig` files and
2. not to have to handle the things twice between `PayloadsXxx` entries in the file and keys in the plugin?

- I figured out that `redeploy_on_update` should only apply if a configuration profile is modified?

In my test, it seems that the configuration will be redeployed even if there's no change in the plan.

- Self Service options missing? 

The button name is not customizable. 

And Is it possible also to add the icon support (and for policies too 😉)

**Comment by ShocOne** [comment]
not in the short  to medium term. the way we need to handle the stating of config profiles,  the jamf pro key insertions and suppress the differences requires that the plist needs to be configured to a minimum level beforehand. there's discussions on having a none plist approach to config profiles within the provider @w0de was considering which would mean you write the key value pairs directly into the .hcl file. But that work hasn't been undertaken as of yet. 

I'd like to understand a bit more about this point. 

> In my test, it seems that the configuration will be redeployed even if there's no change in the plan.

Is this a terraform plan thing, or are you observing that the mdm profile is redeployed by jamf pro ?

> Self Service options missing?

 - no it works. what specifically are you referring to ? the macos examples demonstrate how to use this block.

> And Is it possible also to add the icon support (and for policies too 😉)

- it's unlikely. the api is rubbish for icons and barely works with scripts let alone tf. so until such time jamf fix things on their end this won't be possible.

**Comment by ecanault** [comment]
Hi,

For this point:

>> In my test, it seems that the configuration will be redeployed even if there's no change in the plan.

> Is this a terraform plan thing, or are you observing that the mdm profile is redeployed by jamf pro ?

The profile is redeployed by Jamf Pro.

Here is the `.tf` file:

```
resource "jamfpro_macos_configuration_profile_plist" "jamfpro_macos_configuration_profile_001" {
  name                = "tf-localtest-contentcaching-plist-source:jamfpro-1"
  description         = "An example mobile device configuration profile."
  level               = "System"
  distribution_method = "Install Automatically" // "Make Available in Self Service", "Install Automatically"
  payloads            = file("./cp_disable_softwareupdate.mobileconfig")
  user_removable      = false
  redeploy_on_update  = "All"

  site {
    id = -1
  }

  scope {
    all_computers = true
    all_jss_users = false

  }
}
```

Each `apply` look like this **without any changes**:

````
  # jamfpro_macos_configuration_profile_plist.jamfpro_macos_configuration_profile_001 will be updated in-place
  ~ resource "jamfpro_macos_configuration_profile_plist" "jamfpro_macos_configuration_profile_001" {
        id                  = "272"
        name                = "tf-localtest-contentcaching-plist-source:jamfpro-1"
      ~ redeploy_on_update  = "Newly Assigned" -> "All"
        # (6 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

And I can see in Jamf Pro that:

- The profile has been edited:

<img width="888" alt="History_for_macOS_Configuration_Profile_tf-localtest-contentcaching-plist-source_jamfpro-1__" src="https://github.com/deploymenttheory/terraform-provider-jamfpro/assets/45207371/ded08d33-2fe6-41e4-94c0-ece85c8fd23d">

- And it has been redeployed; and I can confirm that it's the case on Mac itself:

<img width="1291" alt="tf-localtest-contentcaching-plist-source_jamfpro-1__" src="https://github.com/deploymenttheory/terraform-provider-jamfpro/assets/45207371/5447b4fe-5f97-4137-bcbc-a84acf96538c">

**Comment by ecanault** [comment]
For this point:

>> Self Service options missing?

> no it works. what specifically are you referring to ? the macos examples demonstrate how to use this block.

Sorry, I wanted to talk about the *Self Service Display Name*; I think it is missing:

<img width="781" alt="Edit_macOS_Configuration_Profile_tf-localtest-contentcaching-plist-source_jamfpro-1__" src="https://github.com/deploymenttheory/terraform-provider-jamfpro/assets/45207371/da90a95c-d1b1-4a25-9147-de8d4fa27ced">

**Comment by ShocOne** [comment]
> Hi,
> 
> For this point:
> 
> > > In my test, it seems that the configuration will be redeployed even if there's no change in the plan.
> 
> > Is this a terraform plan thing, or are you observing that the mdm profile is redeployed by jamf pro ?
> 
> The profile is redeployed by Jamf Pro.
> 
> Here is the `.tf` file:
> 
> ```
> resource "jamfpro_macos_configuration_profile_plist" "jamfpro_macos_configuration_profile_001" {
>   name                = "tf-localtest-contentcaching-plist-source:jamfpro-1"
>   description         = "An example mobile device configuration profile."
>   level               = "System"
>   distribution_method = "Install Automatically" // "Make Available in Self Service", "Install Automatically"
>   payloads            = file("./cp_disable_softwareupdate.mobileconfig")
>   user_removable      = false
>   redeploy_on_update  = "All"
> 
>   site {
>     id = -1
>   }
> 
>   scope {
>     all_computers = true
>     all_jss_users = false
> 
>   }
> }
> ```
> 
> Each `apply` look like this **without any changes**:
> 
> ```
>   # jamfpro_macos_configuration_profile_plist.jamfpro_macos_configuration_profile_001 will be updated in-place
>   ~ resource "jamfpro_macos_configuration_profile_plist" "jamfpro_macos_configuration_profile_001" {
>         id                  = "272"
>         name                = "tf-localtest-contentcaching-plist-source:jamfpro-1"
>       ~ redeploy_on_update  = "Newly Assigned" -> "All"
>         # (6 unchanged attributes hidden)
> 
>         # (2 unchanged blocks hidden)
>     }
> 
> Plan: 0 to add, 1 to change, 0 to destroy.
> ```
> 
> And I can see in Jamf Pro that:
> 
> * The profile has been edited:
> 
> <img alt="History_for_macOS_Configuration_Profile_tf-localtest-contentcaching-plist-source_jamfpro-1__" width="888" src="https://private-user-images.githubusercontent.com/45207371/336019551-ded08d33-2fe6-41e4-94c0-ece85c8fd23d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODE2ODgsIm5iZiI6MTcxNzQ4MTM4OCwicGF0aCI6Ii80NTIwNzM3MS8zMzYwMTk1NTEtZGVkMDhkMzMtMmZlNi00MWU0LTk0YzAtZWNlODVjOGZkMjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA2MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NjI3MmE0OTVlMjY0NjJhOTQ1ZThmYWFkMDUyOTRkMmRhNTkyY2NlOTM2NDY0ODExMmEyMDE5M2QzYmM5M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BPzK-oMPrLn5m_OSq_qO45ss99kMyt4-cAoa9A-vFcs">
> * And it has been redeployed; and I can confirm that it's the case on Mac itself:
> 
> <img alt="tf-localtest-contentcaching-plist-source_jamfpro-1__" width="1291" src="https://private-user-images.githubusercontent.com/45207371/336020450-5447b4fe-5f97-4137-bcbc-a84acf96538c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODE2ODgsIm5iZiI6MTcxNzQ4MTM4OCwicGF0aCI6Ii80NTIwNzM3MS8zMzYwMjA0NTAtNTQ0N2I0ZmUtNWY5Ny00MTM3LWJjYmMtYTg0YWNmOTY1MzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA2MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiM2Q4NTZmZDYzZjFjZDQzNzgxZDIxZmQ2NGEwOGYzNzNiYWRmNWE4YzhhZGMwZTY2NjI3ZDJlOTlmYTM5ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XKXZ3VoKMmiLPh45ARnMuT7mA8uJEvb9l01PUyQrTos">

This suggests that the reploy_on field is the root of the issue. Any change in the tf plan triggers a uuid change on the jamf side and this in turn triggers a redeployment of the config profile. I'll take a look at this once i have worked through the backlog for 11.5 package updates in the sdk

**Comment by ShocOne** [comment]
As of my testing with jamf pro 11.7, the behaviour for field `"redeploy_on_update"` , is now always to set to `Newly Assigned` . We have therefore taken the decision to make this field computed going forward and it will no longer be configurable within the HCL.
