### ISSUE TITLE
Issue: configuration profiles

### ISSUE THREAD

**Issue by ecanault** [deploymenttheory/terraform-provider-jamfpro#285]
Hi,

Perhaps a bug in configuration profiles regarding exclusions in `scope`?

The provider accepts the following:

```
    scope {
        all_computers      = true
        all_jss_users      = false
        building_ids       = []
        computer_group_ids = []
        computer_ids       = []
        department_ids     = []
        jss_user_group_ids = []
        jss_user_ids       = []
    }
```

This one is also accepted:

```
    scope {
        all_computers      = true
        all_jss_users      = false
        building_ids       = []
        computer_group_ids = []
        computer_ids       = []
        department_ids     = []
        jss_user_group_ids = []
        jss_user_ids       = []
        exclusions {
            building_ids                         = []
            computer_group_ids                   = [
                208,
            ]
            computer_ids                         = []
            department_ids                       = []
            directory_service_or_local_usernames = []
            directory_service_usergroup_ids      = []
            ibeacon_ids                          = []
            jss_user_group_ids                   = []
            jss_user_ids                         = []
            network_segment_ids                  = []
        }
    }
```

But not this one:

```
    scope {
        all_computers      = true
        all_jss_users      = false
        building_ids       = []
        computer_group_ids = []
        computer_ids       = []
        department_ids     = []
        jss_user_group_ids = []
        jss_user_ids       = []
        exclusions {
            building_ids                         = []
            computer_group_ids                   = []
            computer_ids                         = []
            department_ids                       = []
            directory_service_or_local_usernames = []
            directory_service_usergroup_ids      = []
            ibeacon_ids                          = []
            jss_user_group_ids                   = []
            jss_user_ids                         = []
            network_segment_ids                  = []
        }
    }
```

It's OK to have `computer_group_ids` to be empty for main targets, but not in the `exclusions`.

Thanks,
Emmanuel

**Comment by thejoeker12** [comment]
@ShocOne

**Comment by ShocOne** [comment]
hi there, been working through the issue backlog. the reason for your observation is that since your exclusions block in example 3 is in its entirety is empty it will state like this 

`"scope": [
              {
                "all_computers": true,
                "all_jss_users": false,
                "building_ids": [],
                "computer_group_ids": [],
                "computer_ids": [],
                "department_ids": [],
                "exclusions": [],
                "jss_user_group_ids": [],
                "jss_user_ids": [],
                "limitations": []
              }
            ],`
      

This is not a bug, rather it's intentional. we only state things that exit, not things that are empty. therefore only include scoping information that you intend to set, else don't include it within the hcl. it's not required.
  The reason why this works
  
      scope {
        all_computers      = true
        all_jss_users      = false
        building_ids       = []
        computer_group_ids = []
        computer_ids       = []
        department_ids     = []
        jss_user_group_ids = []
        jss_user_ids       = []
    }
    
 Is that the values, `all_computers      = true / all_jss_users      = false` exist within the block. Therefore because something exists, the block will never throw state warnings.
    
The rule of thumb is, only set scope that you need, else don't include it.
