### ISSUE TITLE
Issue: Casper Admin Privileges

### ISSUE THREAD

**Issue by thejoeker12** [deploymenttheory/terraform-provider-jamfpro#292]
As it stands there is validation which forces you to supply casper_admin_privileges when certain permissions are set.

When making accounts, you get looping plans with changes to add casper_admin_privileges as they're not returned in the XML from Jamf. Example: 

`<?xml version="1.0" ?>
<account>
        <id>505</id>
        <name>TF-JL-FULLTEST-1</name>
        <directory_user>false</directory_user>
        <full_name>micky mouse</full_name>
        <email>exampleEmailthing@domain.com</email>
        <email_address>exampleEmailthing@domain.com</email_address>
        <password_sha256>********************</password_sha256>
        <enabled>Enabled</enabled>
        <force_password_change>true</force_password_change>
        <access_level>Full Access</access_level>
        <privilege_set>Custom</privilege_set>
        <privileges>
                <jss_objects>
                        <privilege>Create Scripts</privilege>
                        <privilege>Read Scripts</privilege>
                        <privilege>Update Scripts</privilege>
                        <privilege>Delete Scripts</privilege>
                        <privilege>Create Directory Bindings</privilege>
                        <privilege>Read Directory Bindings</privilege>
                        <privilege>Update Directory Bindings</privilege>
                        <privilege>Delete Directory Bindings</privilege>
                        <privilege>Create Printers</privilege>
                        <privilege>Read Printers</privilege>
                        <privilege>Update Printers</privilege>
                        <privilege>Delete Printers</privilege>
                        <privilege>Create Dock Items</privilege>
                        <privilege>Read Dock Items</privilege>
                        <privilege>Update Dock Items</privilege>
                        <privilege>Delete Dock Items</privilege>
                        <privilege>Create Packages</privilege>
                        <privilege>Read Packages</privilege>
                        <privilege>Update Packages</privilege>
                        <privilege>Delete Packages</privilege>
                        <privilege>Create Categories</privilege>
                        <privilege>Read Categories</privilege>
                        <privilege>Update Categories</privilege>
                        <privilege>Delete Categories</privilege>
                </jss_objects>
                <jss_settings>
                        <privilege>Read SSO Settings</privilege>
                        <privilege>Update User-Initiated Enrollment</privilege>
                </jss_settings>
                <jss_actions>
                        <privilege>Flush Policy Logs</privilege>
                </jss_actions>
        </privileges>
</account>`

We either need to amend this logic to auto supply the casper privs or omit them from state in all cases. One to discuss.

**Comment by ShocOne** [comment]
These are removed in jamf from 11.6. Jamf admin is deprecated

**Comment by ShocOne** [comment]
resolved as part of release v0.1.8
