### ISSUE TITLE
jamfpro_computer_extension_attribute input_script always has updated in-place 

### ISSUE THREAD

**Issue by kenchan0130** [deploymenttheory/terraform-provider-jamfpro#398]
## Terraform and Provider Version

Terraform Version: 1.9.5
Jamf Pro Provider Version: 0.2.0

## Affected Resource(s)

`jamfpro_computer_extension_attribute`

## Terraform Configuration Files

```hcl
resource "jamfpro_computer_extension_attribute" "sample" {
  name              = "Sample"
  enabled           = true
  inventory_display = "Extension Attributes"
  data_type    = "string"
  input_type   = "script"
  input_script = <<-SHELL
#!/bin/sh
/bin/echo "<result>sample</result>"
SHELL
}
```

## Expected Behavior

Once the apply has succeeded, I want it to be marked as no changes.

## Actual Behavior

```log
  ~ update in-place
Terraform will perform the following actions:
  # jamfpro_computer_extension_attribute.sample will be updated in-place
  ~ resource "jamfpro_computer_extension_attribute" "sample" {
        id                = "27"
      ~ input_script      = <<-EOT
            #!/bin/sh
            /bin/echo "<result>sample</result>"
        EOT
        name              = "Sample"
        # (7 unchanged attributes hidden)
    }
```

## Steps to Reproduce

1. Execute `terraform apply`
2. Execute `terraform apply` again

**Comment by kenchan0130** [comment]
I checked the plan file with `terraform plan -out=tfplan` and it may be a newline code issue.

When terraform updates the script with API, the trailing LF newline code is automatically trimmed by Jamf Pro.

Unfortunately, when updating scripts in Jamf Pro UI, the newline code is forced to be converted to CRLF.

**Comment by ShocOne** [comment]
This appears to be the same issue as we saw some months back when handling script resources. i've added some state handling with a helper like this


```
func normalizeScript(script string) string {
	normalized := strings.Replace(script, "\r\n", "\n", -1)

	return strings.TrimRight(normalized, "\n")
}
```

the initial stating of the object throws a warning but thereafter any differences with trailing whitespace is ignored. We can add to this over time if over scenarios dictate the need for suppression.

**Comment by ShocOne** [comment]
please see v0.3.0, this should resolve the issue
