### ISSUE TITLE
Feature Request: Support new keys for PreStage Enrollments in jamf pro v11.9.0

### ISSUE THREAD

**Issue by mhrono** [deploymenttheory/terraform-provider-jamfpro#400]
In jamf pro v11.9.0, a few new skip items for setup assistant were added in PreStage enrollments to support macOS Sequoia. It'd be great if these could be added to the resource:

- `Intelligence`
- `EnableLockdownMode`
- `Welcome`
- `Wallpaper`

Additionally, macOS version management for PreStage Enrollments is also available starting in v11.9.0:

`prestageMinimumOsTargetVersionType` with options:
- `NO_ENFORCEMENT`
- `MINIMUM_OS_LATEST_VERSION`
- `MINIMUM_OS_LATEST_MAJOR_VERSION`
- `MINIMUM_OS_LATEST_MINOR_VERSION`
- `MINIMUM_OS_SPECIFIC_VERSION`

`minimumOsSpecificVersion`: string (required if the above is set to `MINIMUM_OS_SPECIFIC_VERSION`)

**Comment by ShocOne** [comment]
I've made the necessary updates to the SDK to add these new values into the structs. Testing is looking positive. I'll look at another provider release later this week if i have time. Most likely will be next

**Comment by ShocOne** [comment]
@mhrono please see release v0.3.0. thank you
