### ISSUE TITLE
Errors creating multiple categories

### ISSUE THREAD

**Issue by danjamf** [deploymenttheory/terraform-provider-jamfpro#423]
The more categories in a run, the more likely a 400 failure.
``` Error: failed to create  after retries: failed to create category, error: {"status_code":400,"method":"POST","url":"***/api/v1/categories","message":"API Error Response","raw_response":""}```
Dropping parallelism to 1 seems to fix this. Can we lock the number of threads to this "category" of resource?

**Comment by ShocOne** [comment]
included in release v0.4.0. thanks
