### ISSUE TITLE
Issue: jamfpro_computer_extension_attribute continuously updating

### ISSUE THREAD

**Issue by ecanault** [deploymenttheory/terraform-provider-jamfpro#431]
Hi,

I noticed that a `jamfpro_computer_extension_attribute` resource containing a pop-up menu text choice is always updated each time the terraform plan is applied, even if (of course) the resource has not been updated.

```
  # module.extension_attributes["440E5A6B-BB32-474A-AA22-8285D3A69F13"].jamfpro_computer_extension_attribute.object will be updated in-place
  ~ resource "jamfpro_computer_extension_attribute" "object" {
        id                               = "90"
        name                             = "Status"
      ~ popup_menu_choices               = [
          - "Volé",
          - "Perdu",
            "En stock",
          + "Perdu",
          + "Volé",
        ]
        # (5 unchanged attributes hidden)
    }
```

Sometimes 1 field is marked as "- / +", sometimes (as above) it's 2. I tried to change the order of the fileds in the attribute or use the `sort()` function, without success.

For information, as far as I can see, the behaviour is the same for the `jamfpro_restricted_software` ressource : continuous update even if the resource didn't changed.

Regards,
Emmanuel

**Comment by ShocOne** [comment]
Added a fix for this that will be part of the new release. thanks
