### ISSUE TITLE
Document and improve JSON privilege file dependency for `jamfpro_account_group`

### ISSUE THREAD

**Issue by nstrauss** [deploymenttheory/terraform-provider-jamfpro#435]
Though spelled out in https://github.com/deploymenttheory/terraform-provider-jamfpro/blob/b9737569888a89494e5e66b77fbe97624343a52d/internal/resources/common/jamfprivileges/validate.go, when using `jamfpro_account_group` for the first time without the accompanying privilege sets defined in JSON, the resource fails in a loop like so...

```
Error: failed to load JSS Settings Privileges: no valid privileges file found for any version in privileges
```
It's not clear why the issue occurred or how it should be remediated. I had to dig into the source to get more detail and figure out a fix for myself, which is to add the privileges JSON files to versioned folder which _must_ be named "privileges." The provided tool (https://github.com/deploymenttheory/go-api-sdk-jamfpro/blob/7bf5c0261c629c793eb87e94a497e53034e05029/recipes/privileges/Export_All_Available_Privileges_By_Type_To_Json/Export_All_Available_Privileges_By_Type_To_Json.go) to update these files may not be entirely accessible for folks who don't use Go only a regular basis (not your problem), and the current commit only has privilege definitions for up to 11.7.1 (https://github.com/deploymenttheory/terraform-provider-jamfpro/tree/b9737569888a89494e5e66b77fbe97624343a52d/internal/resources/common/jamfprivileges/privileges/11.7.1) 

Wanted to post the issue to have some discussion before moving forward with any work. It looks like this is known to be a bit quirky already - https://github.com/deploymenttheory/terraform-provider-jamfpro/blob/b9737569888a89494e5e66b77fbe97624343a52d/todo.md?plain=1#L15-L16 This feels like ongoing work for the provider maintainers and admins using `jamfpro_account_group`. Some open questions/ideas...

1. Are the docs like https://github.com/deploymenttheory/terraform-provider-jamfpro/blob/b9737569888a89494e5e66b77fbe97624343a52d/docs/resources/account_group.md auto-generated? If not, what's the preferred heading to add usage notes? Happy to add directions described above to get people started with the resource.
2. Does it make sense to move this validation to the API SDK instead of the provider? Then admins using the provider wouldn't need to add the JSON to their repo/project at all. 
3. Could a GitHub Actions workflow keep the privilege list up to date? Either in the SDK or provider.
4. What are thoughts on adding a provider setting for not validating privileges? The API just fails as it should.
5. A setting for specifying the directory to a path other than "privileges"?

Thanks for all the work the maintainers have done already!

Edit: Specifying hard coded Jamf Pro version constraints is also challenging as it means the updated schema might end up in a versioned folder which doesn't represent privileges for the actual Jamf Pro version. https://github.com/deploymenttheory/terraform-provider-jamfpro/blob/b9737569888a89494e5e66b77fbe97624343a52d/internal/resources/common/jamfprivileges/validate.go#L41-L45 For example, even though I'm not running 11.7.1 or earlier, the folder currently needs to be `privileges/11.7.1` to get the resource to work.

**Comment by ShocOne** [comment]
Please can you provide the hcl you were running that caused this error and your version of jamf pro. To answer your questions:
1. Yes, by the terraform docs generator. The description gets pulled from the schema for the resource.
2. Sort of. Provider operators are not required or expected to add the json privileges to the provider, provider maintainers or provider contributors are however. It would be counter intuitive for admins to have to manually add their permissions to their fork of the provider as well. I'm not clear if that is what you are suggesting? A PR to this project would meet the requirement much quicker. A thought through solution would probably be something described in point 3.
3. Absolutely. Similar to the api client privileges maintenance pipeline. The process for this would be to write a revised sdk recipe that exports the permissions for a gha pipeline usecase, make a folder for the new json exports modify the go consts as you've identified file then pr the results. Then schedule this to run once weekly.
4. From memory it's needed to handle some of the collections of permissions like for administrators. There's also weirdness with the naming convention and sometimes even typos. So my preference is to implement a fully automated approach based of a jamf pro server export.
5. I'm not sure why you'd need this.

**Comment by ShocOne** [comment]
please find an implementation here - https://github.com/deploymenttheory/terraform-provider-jamfpro/blob/main/.github/workflows/user-account-maintenance.yml 

This runs once weekly, calls a script from repo_dir/scripts/maintainence/GetUserAccountPrivileges , generates the new permissions, updates validate.go const's , PR's the result. 

Everything is self contained within the provider with no longer any requirements for external operations to be taken within the sdk and manual copying of the results into the provider.

I'll be version bumping shortly. thanks

**Comment by ShocOne** [comment]
Can you share your hcl please. Im not following your references to json. I can successfully deploy with the recent changes just fine.

**Comment by nstrauss** [comment]
@ShocOne 

Delete _ALL_ references to any privileges JSON from your directory structure and then try to use a resource with a custom privilege set like...

```
resource "jamfpro_account_group" "custom_admin_group" {
  name                    = "custom_admin_group"
  access_level            = "Full Access"
  privilege_set           = "Custom"
  jss_objects_privileges = [
    "Create Advanced Computer Searches",
    "Read Advanced Computer Searches",
    "Update Advanced Computer Searches",
    "Delete Advanced Computer Searches",
  ]

  jss_settings_privileges = [
    "Read Activation Code",
    "Update Activation Code",
    "Read Apache Tomcat Settings",
    "Update Apache Tomcat Settings",
    "Read Apple Configurator Enrollment",
    "Update Apple Configurator Enrollment",
  ]

  jss_actions_privileges = [
    "Allow User to Enroll",
    "Assign Users to Computers",
    "Assign Users to Mobile Devices",
    "Change Password",
    "Dismiss Notifications",
  ]
}
```
What I'm saying is nowhere in the docs is there a mention of JSON files being a requirement for `jamfpro_account_group` and the associated error has no references either. Trying to make it easier for folks to get on a happy path.

**Comment by ShocOne** [comment]
How are you executing terraform, locally or pipeline and are you using the terraform registry in the provider.tf config ? I still don't understand the json statement. The provider is a compiled binary when pulling from the tf registry. There's never a scenario where the exported json privileges are not present ?

**Comment by nstrauss** [comment]
@ShocOne Oh wow, I see what you're saying. Sorry, shows my inexperience with Terraform providers. Yep, have a provider block and running `terraform init` which caches the provider locally to `.terraform/providers/registry.terraform.io/deploymenttheory/jamfpro/0.4.2`

```terraform
terraform {
  required_providers {
    jamfpro = {
      source  = "deploymenttheory/jamfpro"
      version = "0.4.2"
    }
  }
}

provider "jamfpro" {
  jamfpro_instance_fqdn               = var.jamfpro_instance_fqdn
  auth_method                         = "oauth2"
  client_id                           = var.jamfpro_client_id
  client_secret                       = var.jamfpro_client_secret
  jamfpro_load_balancer_lock          = var.jamfpro_jamf_load_balancer_lock
  hide_sensitive_data                 = var.jamfpro_hide_sensitive_data
  token_refresh_buffer_period_seconds = var.jamfpro_token_refresh_buffer_period_seconds
}
```
Not having used golang much I forgot the _entire_ provider is compiled into a single binary, including those JSON files. However, I'm still seeing the same thing. My folder structure is pretty flat...

```
- provider.tf
- account_groups.tf
- privileges
  - 11.10.1
    - jss_actions_privileges.json
    - jss_objects_privileges.json
    - jss_settings_privileges.json
```
If I remove the `privileges` folder and run `terraform plan` I get the error...

```
 Error: failed to load JSS Settings Privileges: error finding privileges folder: privileges folder not found
```
Sounds like for you the provider is correctly finding the folder. If this is just me holding it wrong and no one else is having this problem, I'm fine with that. Sorry to ask, but Is it possible your Jamf Pro Terraform project directory is within a directory which also has those JSON files somewhere in the parent and https://github.com/deploymenttheory/terraform-provider-jamfpro/blob/64755d3c3ee6f843524527c58a0a022b608ffc7e/internal/resources/common/jamfprivileges/validate.go#L155 is finding it? Again, if not I have a working solution and don't need to spend more time on this. Thank you.

**Comment by ShocOne** [comment]
Perfect. That's just what i needed to understand. Thanks for taking the time clarify. I'll fix tomorrow.
