### ISSUE TITLE
Added mutex to all resources for create operations 

### ISSUE THREAD

**Issue by ShocOne** [deploymenttheory/terraform-provider-jamfpro#470]
Jamf pro inconsistently gets overwhelmed by the parallelism of terraform and the speed of Go when creating new resources. It cannot keep up. Consequently this can lead to 409 errors when trying to state. This is an intermittent issue, some time it reliable fails, sometimes it fails randomly. scale of deployment can affect the results. but not always. 

Currently mutex is selectively applied to a subset of resources within the provider to handle for this. The mutex implementation allows for parallelism to persist, but when in a given tf apply run and multiple creates for a given resource type are within a plan, the mutex will will only allow a single create at a time and forces sequential operations for that resources create operations. The impact will be a small slow down in create operations, but this is outweighed by the benefits of reliable requests and reliable stating.

**Comment by ecanault** [comment]
@ShocOne 

For information I still encounter performance issues when creating ~100 resources at a time.

It happens randomly for resources like policies, configuration profiles or restricted software, for 3 to 5 resources.

There is no problem if I put the `parralelism` option to `1`.

Regards, 
Emmanuel

**Comment by ecanault** [comment]
Hi @ShocOne,

It's not consistent: in 0.5.1 it was often with policies, configuration profiles or restricted software.
With version 0.6.0: I tried 2 times with the same plan, and it fails both times on sites creation.

Regards,
Emmanuel

**Comment by ShocOne** [comment]
We spoke with jamf about this issue this week and they said it was due to the caching behaviour in load balanced configurations within jamf cloud. Ultimately, they don't know why this occurs based on the conversations had to date. Jamf use this provider internally and have commented that they only perform runs with parallelism of 1, because of the inconsistent behaviour. we ( the provider devs) are hoping to have some sessions next year with jamf to try and understand some of the specifics, and whether we can implement a bullet proof solution. in the mean time, if you need to do big runs the advice is to run the operation with parallelism of 1.

**Comment by ecanault** [comment]
Thanks for this feedback!
Don't hesitate if I can help.
