### ISSUE TITLE
Enhancement: add Self Service Display Name in jamfpro_macos_configuration_profile_plist and jamfpro_macos_configuration_profile_plist_generator

### ISSUE THREAD

**Issue by ecanault** [deploymenttheory/terraform-provider-jamfpro#471]
Hi,

When deploying configuration profiles via Self Service, Jamf Pro allows the customization the label and the button name.

Like `install_button_text` for the button, is it possible to add `label_text` for the Self Service label in `jamfpro_macos_configuration_profile_plist` and `jamfpro_macos_configuration_profile_plist_generator`?

Thanks,
Emmanuel

**Comment by ShocOne** [comment]
im not aware of what field you are talking about ?

![image](https://github.com/user-attachments/assets/c5804b27-dbf4-442d-a50d-99cf13afbccf)

The button name field already works. label_text doesnt exist ?

A screen would be helpful.

thanks

**Comment by ecanault** [comment]
Hi,

That's it, I don't see the `label_text` for configuring that:

![389917387-c5804b27-dbf4-442d-a50d-99cf13afbccf](https://github.com/user-attachments/assets/aaa248ce-b9ac-4daa-96c8-3e4d7a26fcb4)

In the Classic API the key is called `self_service_display_name` which is different from `name` (the profile name by itself).

Regards,
Emmanuel

**Comment by ShocOne** [comment]
hi there, the hcl should be like this

```
self_service {
    use_for_self_service            = true
    self_service_display_name       = "some deisplay name"
    install_button_text             = "Install"
    reinstall_button_text           = "Reinstall"
    self_service_description        = "a description by tf"
    force_users_to_view_description = false

    feature_on_main_page = false
  }
```

**Comment by ecanault** [comment]
Hi @ShocOne,

Yes it could look like this I think.
You confirm that the new `self_service_display_name` has not been implemented in 0.6.0?

Thanks,
Emmanuel

**Comment by ShocOne** [comment]
hi @ecanault 

it's been in the provider for. number of versions now, i don't remember when it first went in.

here's the full block as an example

```
self_service {
    install_button_text             = "Install - ${var.version_number}"
    self_service_description        = "This is the self service description"
    force_users_to_view_description = true
    feature_on_main_page            = true
    notification                    = false
    notification_subject            = "New Profile Available"
    notification_message            = "A new profile is available for installation."

    self_service_category {
      id         = jamfpro_category.jamfpro_category_array[0].id
      display_in = true
      feature_in = false
    }

    self_service_category {
      id         = jamfpro_category.jamfpro_category_array[1].id
      display_in = true
      feature_in = false
    }

    self_service_category {
      id         = jamfpro_category.jamfpro_category_array[2].id
      display_in = true
      feature_in = false
    }
  }
```

**Comment by ecanault** [comment]
Hmm, I don't see the `self_service_display_name` attribute!?

And here is the output of an `apply` with 0.6.0:

```
 Error: Unsupported argument
│ 
│   on terraform_modules/configuration_profiles/resource_jamfpro_configuration_profiles.tf line 50, in resource "jamfpro_macos_configuration_profile_plist" "object":
│   50:       self_service_display_name       = self_service.value.NAME
│ 
│ An argument named "self_service_display_name" is not expected here.
```

What am I doing wrong?

**Comment by ecanault** [comment]
Bump!
I'm talking about **configuration profiles**, not **policies**! 😉

**Comment by ShocOne** [comment]
ah! - field is notification_subject 

```
self_service {
    install_button_text             = "Install - ${var.version_number}"
    self_service_description        = "This is the self service description"
    force_users_to_view_description = true
    feature_on_main_page            = true
    notification                    = false
    notification_subject            = "New Profile Available"
    notification_message            = "A new profile is available for installation."

    self_service_category {
      id         = jamfpro_category.jamfpro_category_array[0].id
      display_in = true
      feature_in = false
    }

    self_service_category {
      id         = jamfpro_category.jamfpro_category_array[1].id
      display_in = true
      feature_in = false
    }

    self_service_category {
      id         = jamfpro_category.jamfpro_category_array[2].id
      display_in = true
      feature_in = false
    }
  }
```

**Comment by ecanault** [comment]
Strange... and still doesn't work...

<img width="428" alt="Cursor_et_Edit_macOS_Configuration_Profile_cp_disable_softwareupdate__" src="https://github.com/user-attachments/assets/a47c53d4-b3d2-413b-87cb-cd4cc5eb7c0b">

By the way it seems the `notification` doesn't work neither, setting to `true` doesn't toggle the checkbox in the Jamf Pro GUI. I had to check it manually in the capture above.
