### ISSUE TITLE
Bug: 0.6.1 Policy State Migrating not working

### ISSUE THREAD

**Issue by smithjw** [deploymenttheory/terraform-provider-jamfpro#511]
Might be an error with the state migration logic here. When I upgrade to 0.6.1 and run a plan, the provider wants to recreate all of my existing policies.

**Comment by ShocOne** [comment]
Can you share your logs please ? Thanks

**Comment by ShocOne** [comment]
i've been able to isolate the issue. there will be a fix in the next point release that will correctly state migrate and not attempt a resource recreate.
