### ISSUE TITLE
Add handling for "Duplicate Name" scenarios

### ISSUE THREAD

**Issue by ShocOne** [deploymenttheory/terraform-provider-jamfpro#84]
Add handling for scenarios where a resource already exists in jamf and has the same resource name. 

Solution should provide the ability to skip resources with the same name, or, optionally delete resources with the same name and then redeploy with the hcl based configuration.

**Comment by smithjw** [comment]
I've run into this when pushing many new EAs into Jamf. In these cases, I ran a `terraform apply` where the majority of items created successfully but errored with "Root resource was present, but now absent". 

Running a subsequent `apply` failed and I either had to delete the resource manually, or import the EA to get things into sync between Jamf and my state file.

**Comment by ShocOne** [comment]
in version v0.0.41 i've added for some new waitfor logic that accounts for server settle down time when creating new resources. EA's in particular take a disproportionate amount of time to become statable into terraform especially when trying to deploy many at the same time. the fixes in the new release during testing successfully supported the creation of 50 EA's along with 20 scripts and 20 printers. Please test the new version and feedback if the issue persists with how many many and what resources during the deployment failed. many thanks
